/**
 * AIPortfolioPDFGenerator.js
 * Zero-Dependency Pure Node.js AI Portfolio PDF Generator.
 * Generates a clean, valid PDF file (.pdf) directly from the AI Portfolio object
 * without requiring any third-party npm packages.
 */

'use strict';

const fs = require('fs');

class AIPortfolioPDFGenerator {
  /**
   * Escape text for PDF text stream syntax: (text)
   */
  _escapePdfText(text) {
    if (!text) return '';
    return String(text)
      .replace(/\\/g, '\\\\')
      .replace(/\(/g, '\\(')
      .replace(/\)/g, '\\)')
      .replace(/[^\x20-\x7E]/g, ' '); // ASCII clean
  }

  /**
   * Generate a PDF file from a portfolio object.
   * @param {Object} portfolio - Output from AIPortfolioGeneratorModel
   * @param {string} outputPath - Output file path (.pdf)
   * @returns {string} Absolute path of generated PDF
   */
  generatePDF(portfolio, outputPath) {
    const p = portfolio || {};
    const name       = p.name || 'Student Portfolio';
    const tagline    = p.tagline || 'Campus Student';
    const univ       = p.university || '';
    const dept       = p.department || '';
    const summary    = p.aiSummary || '';
    const stats      = p.stats || {};
    const skills     = p.skills || [];
    const certs      = p.verifiedAchievements || [];

    // Construct text stream lines
    const streamLines = [];
    let y = 780; // Top margin on A4 (595 x 842 pt)

    // Header
    streamLines.push(`BT /F2 22 Tf 50 ${y} Td (${this._escapePdfText(name)}) Tj ET`);
    y -= 25;
    streamLines.push(`BT /F1 12 Tf 50 ${y} Td (${this._escapePdfText(tagline + (univ ? ' | ' + univ : ''))}) Tj ET`);
    y -= 18;
    if (dept) {
      streamLines.push(`BT /F1 10 Tf 50 ${y} Td (${this._escapePdfText('Department: ' + dept)}) Tj ET`);
      y -= 25;
    } else {
      y -= 10;
    }

    // Divider Line
    streamLines.push(`0.7 0.7 0.7 RG 50 ${y} m 545 ${y} l S`);
    y -= 30;

    // AI Summary Section
    streamLines.push(`BT /F2 14 Tf 50 ${y} Td (EXECUTIVE SUMMARY) Tj ET`);
    y -= 20;

    // Wrap summary text
    const summaryWords = summary.split(' ');
    let currentLine = '';
    for (const word of summaryWords) {
      if ((currentLine + ' ' + word).length > 85) {
        streamLines.push(`BT /F1 10 Tf 50 ${y} Td (${this._escapePdfText(currentLine)}) Tj ET`);
        y -= 15;
        currentLine = word;
      } else {
        currentLine = currentLine ? currentLine + ' ' + word : word;
      }
    }
    if (currentLine) {
      streamLines.push(`BT /F1 10 Tf 50 ${y} Td (${this._escapePdfText(currentLine)}) Tj ET`);
      y -= 25;
    }

    // Portfolio Stats
    streamLines.push(`BT /F2 14 Tf 50 ${y} Td (PORTFOLIO STATS) Tj ET`);
    y -= 20;
    const statText = `Verified Certificates: ${stats.verifiedCertificates || 0}  |  Hackathons Won: ${stats.hackathonsWon || 0}  |  Skills Acquired: ${stats.skillsAcquired || skills.length}`;
    streamLines.push(`BT /F1 10 Tf 50 ${y} Td (${this._escapePdfText(statText)}) Tj ET`);
    y -= 30;

    // Skills Matrix
    streamLines.push(`BT /F2 14 Tf 50 ${y} Td (EVIDENCE-BACKED SKILLS) Tj ET`);
    y -= 20;

    if (skills.length > 0) {
      for (const s of skills.slice(0, 10)) {
        const skillName = typeof s === 'string' ? s : s.name;
        const cat = s.category ? ` [${s.category}]` : '';
        const ev = s.supportedBy ? ` (Evidence: ${s.supportedBy.join(', ')})` : '';
        streamLines.push(`BT /F1 10 Tf 55 ${y} Td (* ${this._escapePdfText(skillName + cat + ev)}) Tj ET`);
        y -= 16;
      }
    } else {
      streamLines.push(`BT /F1 10 Tf 55 ${y} Td ((No verified skills recorded yet)) Tj ET`);
      y -= 16;
    }
    y -= 15;

    // Verified Credentials & Achievements
    streamLines.push(`BT /F2 14 Tf 50 ${y} Td (VERIFIED CREDENTIALS & ACHIEVEMENTS) Tj ET`);
    y -= 20;

    if (certs.length > 0) {
      for (const c of certs.slice(0, 8)) {
        const title = c.title || 'Certificate';
        const org   = c.organization ? ` - ${c.organization}` : '';
        const date  = c.date ? ` (${c.date})` : '';
        const badge = c.badge ? ` [${c.badge}]` : '';
        streamLines.push(`BT /F2 10 Tf 55 ${y} Td ([+] ${this._escapePdfText(title + org + date + badge)}) Tj ET`);
        y -= 15;

        if (c.credentialId) {
          streamLines.push(`BT /F1 9 Tf 70 ${y} Td (${this._escapePdfText('Credential ID: ' + c.credentialId)}) Tj ET`);
          y -= 14;
        }
      }
    } else {
      streamLines.push(`BT /F1 10 Tf 55 ${y} Td ((No certificates added yet)) Tj ET`);
      y -= 16;
    }

    // Footer
    streamLines.push(`0.8 0.8 0.8 RG 50 40 m 545 40 l S`);
    streamLines.push(`BT /F1 8 Tf 50 28 Td (${this._escapePdfText('Generated by Campus Clubs & Events AI Portfolio Engine — Verifiable Record')}) Tj ET`);

    const streamContent = streamLines.join('\n');
    const streamLength = Buffer.byteLength(streamContent, 'utf-8');

    // Build raw PDF objects
    const pdfObjects = [];
    pdfObjects.push('%PDF-1.4');
    pdfObjects.push('1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj');
    pdfObjects.push('2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj');
    pdfObjects.push('3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>\nendobj');
    pdfObjects.push('4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj');
    pdfObjects.push('5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>\nendobj');
    pdfObjects.push(`6 0 obj\n<< /Length ${streamLength} >>\nstream\n${streamContent}\nendstream\nendobj`);

    // Calculate xref table
    let offset = 0;
    const offsets = [0];
    for (let i = 0; i < pdfObjects.length; i++) {
      offsets.push(offset);
      offset += Buffer.byteLength(pdfObjects[i], 'utf-8') + 1; // +1 for newline
    }

    const xrefStart = offset;
    const xrefLines = ['xref', `0 ${pdfObjects.length + 1}`, '0000000000 65535 f '];
    for (let i = 1; i <= pdfObjects.length; i++) {
      const offStr = String(offsets[i]).padStart(10, '0');
      xrefLines.push(`${offStr} 00000 n `);
    }

    const trailer = [
      'trailer',
      `<< /Size ${pdfObjects.length + 1} /Root 1 0 R >>`,
      'startxref',
      String(xrefStart),
      '%%EOF'
    ];

    const pdfBuffer = [...pdfObjects, ...xrefLines, ...trailer].join('\n');
    fs.writeFileSync(outputPath, pdfBuffer, 'utf-8');

    return outputPath;
  }
}

module.exports = AIPortfolioPDFGenerator;
